In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [5]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a.ndim

1

In [8]:
a[1:5]

array([2, 3, 4, 5])

In [10]:
a[2:7]

array([3, 4, 5, 6, 7])

In [11]:
a[4:]

array([5, 6, 7, 8, 9])

In [12]:
a[:5]

array([1, 2, 3, 4, 5])

In slicing the end index position is not printed 
if not assigned upto where to print it prints all the reamining values ..and if not assigned where to begin its starts from the first to where its assigned to end 
And in step slicing  as below; 2 is the nmber of steps then 1 is index where to begin and 6 is end


In [13]:
a[1:6:2]

array([2, 4, 6])

#slice 2D Array

In [14]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [15]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
b[1,1:4]

array([7, 8, 9])

In [17]:
b[0,0:3]

array([1, 2, 3])