In [3]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5])


In [6]:
a.shape

(5,)

In [7]:
b=np.array([[1,2,3,4],[5,6,7,8]])

In [8]:
b.shape

(2, 4)

In [9]:
c=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [10]:
new_arr=c.reshape(4,3)


In [11]:
new_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
c.shape

(12,)

In [14]:
new_arr.shape


(4, 3)

In [15]:
   new_arr2=c.reshape(6,2)

In [16]:
new_arr2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [23]:
twoD_array=np.array([[1,2,3,],[4,5,6]])

In [24]:
flatten_array = twoD_array.reshape(-1)

In [25]:
flatten_array

array([1, 2, 3, 4, 5, 6])

In [26]:
flatten_array.shape

(6,)